### ISSUE TITLE
Old images on quay.

### ISSUE THREAD

**Issue by pigmej** [piraeusdatastore/piraeus#11]
Hey,

Despite of fixes I see that all images even with `latest` tag are old on quay.io. Do you guys have any procedure to update them?

**Comment by rck** [comment]
Outdated because of old versions of SW included by default that are not used anyways and therefore do not matter anyways? Yes, that could be.

Otherwise most of the images should be up to date with the relevant versions released upstream (e.g., piraeus-server contains the most recent version of LINSTOR). The piraeus-init container is an exception, it is currently all work in progress.

Still, all in all we need to further automate image creation/update, that is true. It is a young project, it has rough edges here and there.

**Comment by pigmej** [comment]
@rck hey,

So despite merged fix for ubuntu https://github.com/piraeusdatastore/piraeus/pull/10 and it's obviously not yet included in the images. So yes the issue is more about the piraeus components than linstor components.

**Comment by rck** [comment]
> The piraeus-init container is an exception, it is currently all work in progress.

I will push a +1 version later today

**Comment by rck** [comment]
v0.2 pushed and deploy yamls updated
