### ISSUE TITLE
modinfo 8.4.10 vs. kernel-loader 9.0.27

### ISSUE THREAD

**Issue by phoenix-bjoern** [piraeusdatastore/piraeus#63]
We are using Ubuntu 18.04 bionic. `modinfo drbd` shows the version 8.4.10 while the kernel loader show a different version:

```docker run -it --rm --privileged \
>    -v /lib/modules:/lib/modules -v /usr/src:/usr/src:ro \
>    -e "LB_INSTALL=yes" \
>    piraeusdatastore/drbd9-bionic:latest
DRBD module is already loaded

DRBD version loaded:
version: 9.0.27-1 (api:2/proto:86-118)
GIT-hash: bea41a056bb2abe4d5dfd2f69863282dfa1b2257 build by @de-fra-node38, 2021-01-21 10:18:25
Transports (api:16): tcp (9.0.27-1)
```

What is now the actual version? And how to release the version conflict?

**Comment by rck** [comment]
The 8.4.10 (from modinfo) is the one your distribution ships. Piraeus/LINSTOR *requires* a 9.x.y module. And that is what the module loader built and inserted for you.

**Comment by phoenix-bjoern** [comment]
Yes, this is what we suspected as well. But how can we check which module is actually used? The Docker container checks the output of `cat /proc/drbd` which shows 9.0.27, while modinfo shows the older version. Which one is active?
And: Is it necessary to get them in sync and so, how can we do that?

**Comment by rck** [comment]
hm, are you sure you know what `modinfo` is and what it does? it shows information about the module "it would load" from `/lib/modules/$version`. And usually this is what you end up using when you use `modprobe`. But if you `insmod` a module, the actual version you inserted has nothing to do with what `modinfo` gives you, that is just not what `modinfo` does.

The one from `cat /proc/drbd` is active. always.

The ways how to use this are:
- don't load the drbd module on the host as this would be the too old one and let the module load container compile/insert the module for you via `insmod`. Don't care about `modinfo`.
-  install a drbd 9 kernel module (e.g., 9.0.27) on your host (depends on how you do that, don't forget `depmod`), and load this "blessed" module at boot. If you installed it correctly, the `*.ko` will end in an "update" directory (every distri calles it differently), and `modprobe` (and yes then also `modinfo`) will pick it up. Then you don't need to use the module load container because you already have a drbd 9 module loaded. The loader then basically is a NOOP. You can and should still use the load container as it also makes sure other modules get loaded (lvm,...).

`modinfo` and `cat /proc/drbd` will only be in sync if you install the module on the host. If you don't, it gets `insmod`ed by the container and `modinfo` does not know or care about it at all. HTH

**Comment by phoenix-bjoern** [comment]
Thanks for clarification, then we should be good :-)
